### ISSUE TITLE
Revamp UX and design of the leaderboard UI

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/oss-leaderboard#24]
**Current UI**
Link - https://oss-board.netlify.app

![image](https://user-images.githubusercontent.com/3315763/94771025-f64b9d00-03d5-11eb-97b6-b10570b5f394.png)

- Need a visual makeover and UX improvements.
- Ability to add logo
- Usernames should have links to their github profiles
- Show the time range: from and to (the time date range for the data)
- Show the as of date (last updated) - the date when the leaderboard was updated.

**Comment by kabirbaidhya** [comment]
@Swechhya @yankeexe @aanchal-adk Add in your thoughts or suggestions if you have any.

**Comment by ishan-me** [comment]
Submitted my pull request **#26**

**Comment by ishan-me** [comment]
Addressed comments received to the pull request **#26**
